version: '3.8'

services:

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-fastapi
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - backend

networks:
  backend:
    driver: bridge
