"""initial migrations

Revision ID: a60dcd3e2dc0
Revises: 0fa96fc18aca
Create Date: 2024-10-29 21:41:41.626274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a60dcd3e2dc0'
down_revision: Union[str, None] = '0fa96fc18aca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
