"""add fields phone and code

Revision ID: e34b86181468
Revises: b002a6397fe1
Create Date: 2024-10-15 01:54:11.449178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e34b86181468'
down_revision: Union[str, None] = 'b002a6397fe1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('code', sa.Integer(), nullable=True))
    op.alter_column('clients', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.create_unique_constraint(None, 'clients', ['phone'])
    op.drop_column('clients', 'context')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('context', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'clients', type_='unique')
    op.alter_column('clients', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('clients', 'code')
    op.drop_column('clients', 'phone')
    # ### end Alembic commands ###
